name: privilege
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.20.1=hf9c8cef_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libcurl=7.87.0=h6312ad2_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=1.1.1w=hd590300_0
  - pycurl=7.44.1=py38h996a351_1
  - pydispatcher=2.0.5=py_1
  - pyodbc=4.0.32=py38h709712a_1
  - python=3.8.15=h257c98d_0_cpython
  - python_abi=3.8=8_cp38
  - readline=8.3=h853b02a_0
  - tk=8.6.13=noxft_ha0e22de_103
  - unixodbc=2.3.14=h69e2008_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - alabaster==0.7.12
    - annotated-types==0.6.0
    - anyio==3.5.0
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.2
    - astroid==2.6.6
    - astropy==5.0.4
    - asttokens==3.0.1
    - async-timeout==4.0.1
    - atomicwrites==1.4.0
    - attrs==25.3.0
    - autocfg==0.0.8
    - automat==24.8.1
    - autopep8==1.6.0
    - babel==2.9.1
    - backcall==0.2.0
    - backports-functools-lru-cache==1.6.4
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.2.0
    - beautifulsoup4==4.11.1
    - binaryornot==0.4.4
    - bitarray==2.4.1
    - bkcharts==0.2
    - black==19.10b0
    - bleach==4.1.0
    - blinker==1.4
    - bokeh==2.4.2
    - boto3==1.21.32
    - botocore==1.24.32
    - bottleneck==1.3.4
    - brotlipy==0.7.0
    - cachetools==4.2.2
    - certifi==2021.10.8
    - cffi==1.15.0
    - chardet==4.0.0
    - charset-normalizer==2.0.4
    - click==8.0.4
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - colorcet==2.0.6
    - comm==0.2.3
    - conda-pack==0.6.0
    - constantly==15.1.0
    - contourpy==1.1.1
    - cookiecutter==1.7.3
    - cryptography==46.0.3
    - cssselect==1.1.0
    - cycler==0.11.0
    - cython==0.29.28
    - cytoolz==0.11.0
    - daal==2024.5.0
    - daal4py==2024.5.0
    - dask==2022.2.1
    - datashader==0.13.0
    - datashape==0.5.2
    - debugpy==1.8.19
    - decorator==5.2.1
    - defusedxml==0.7.1
    - diff-match-patch==20241021
    - distributed==2022.2.1
    - distro==1.9.0
    - docstring-to-markdown==0.17
    - docutils==0.20.1
    - entrypoints==0.4
    - et-xmlfile==2.0.0
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.16.1
    - fonttools==4.57.0
    - frozenlist==1.5.0
    - fsspec==2025.3.0
    - ftfy==6.2.3
    - google-auth==2.47.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.70.0
    - h11==0.16.0
    - heapdict==1.0.1
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - hyperlink==21.0.0
    - idna==3.11
    - imageio==2.35.1
    - imagesize==1.4.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - incremental==24.11.0
    - ipykernel==6.17.1
    - ipython==8.8.0
    - ipython-genutils==0.2.0
    - isort==5.13.2
    - itemadapter==0.9.0
    - itemloaders==1.3.2
    - jedi==0.19.1
    - jeepney==0.9.0
    - jinja2-time==0.2.0
    - jmespath==1.0.1
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==7.3.4
    - jupyter-core==5.0.0
    - jupyter-server==1.24.0
    - jupyterlab-pygments==0.3.0
    - kiwisolver==1.4.7
    - lazy-object-proxy==1.10.0
    - llvmlite==0.38.1
    - locket==1.0.0
    - lxml==6.0.2
    - markdown==3.7
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.7
    - mccabe==0.6.1
    - mistune==0.8.4
    - msgpack==1.1.1
    - multidict==6.1.0
    - multipledispatch==1.0.0
    - nbclassic==0.3.5
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - networkx==2.7.1
    - nltk==3.7
    - nose==1.3.7
    - notebook==6.4.8
    - numba==0.55.1
    - numexpr==2.8.1
    - numpy==1.21.5
    - numpydoc==1.2
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-nccl-cu12==2.20.5
    - oauthlib==3.2.2
    - olefile==0.46
    - open-clip-torch==2.20.0
    - openai==1.10.0
    - opencv-python==4.7.0.72
    - openpyxl==3.0.9
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - panel==0.13.0
    - param==1.12.0
    - parsel==1.6.0
    - parso==0.8.3
    - partd==1.2.0
    - pathspec==0.7.0
    - patsy==0.5.2
    - pep8==1.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - pip==21.2.4
    - pkginfo==1.8.2
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - plotly==5.6.0
    - pluggy==1.0.0
    - portalocker==2.7.0
    - pot==0.9.0
    - poyo==0.5.0
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.20
    - propcache==0.2.0
    - protego==0.1.16
    - protobuf==3.20.3
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.7.0
    - pycosat==0.6.3
    - pycparser==2.21
    - pyct==0.4.6
    - pydantic==2.6.0
    - pydantic-core==2.16.1
    - pydocstyle==6.1.1
    - pyerfa==2.0.0
    - pyflakes==2.3.1
    - pygments==2.11.2
    - pyhamcrest==2.0.2
    - pyjwt==2.1.0
    - pylint==2.9.6
    - pyls-spyder==0.4.0
    - pyopenssl==25.3.0
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - python-lsp-jsonrpc==1.1.2
    - python-lsp-server==1.12.2
    - python-slugify==8.0.4
    - pytz==2025.2
    - pyviz-comms==3.0.6
    - pywavelets==1.4.1
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - queuelib==1.7.0
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.4
    - requests-file==3.0.1
    - requests-oauthlib==2.0.0
    - rpds-py==0.20.1
    - rsa==4.9.1
    - s3transfer==0.5.0
    - safetensors==0.3.1
    - scikit-image==0.19.2
    - scikit-learn-intelex==2024.5.0
    - scipy==1.7.3
    - scrapy==2.6.1
    - seaborn==0.11.2
    - secretstorage==3.3.1
    - send2trash==1.8.0
    - sentencepiece==0.1.99
    - service-identity==18.1.0
    - setuptools==61.2.0
    - six==1.17.0
    - sniffio==1.3.1
    - snowballstemmer==3.0.1
    - sortedcontainers==2.4.0
    - soupsieve==2.7
    - sphinx==7.1.2
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stack-data==0.6.3
    - tbb==2021.13.1
    - tblib==1.7.0
    - tenacity==8.0.1
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-logger==0.1.0
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.13.1
    - testpath==0.5.0
    - text-unidecode==1.3
    - textdistance==4.2.1
    - threadpoolctl==2.2.0
    - three-merge==0.1.1
    - tifffile==2021.7.2
    - timm==0.6.12
    - tinycss==0.4
    - tldextract==3.2.0
    - tokenizers==0.13.3
    - toml==0.10.2
    - tomli==1.2.2
    - toolz==0.11.2
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu113
    - torchvision==0.13.1+cu113
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.1.1
    - transformers==4.27.4
    - triton==3.0.0
    - twisted==22.2.0
    - typed-ast==1.4.3
    - typing-extensions==4.9.0
    - tzdata==2025.3
    - ujson==5.1.0
    - unidecode==1.2.0
    - urllib3==1.26.9
    - w3lib==1.21.0
    - watchdog==2.1.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==0.58.0
    - werkzeug==2.0.3
    - wheel==0.37.1
    - widgetsnbextension==3.5.2
    - wrapt==1.12.1
    - wurlitzer==3.0.2
    - xarray==0.20.1
    - xlrd==2.0.1
    - xlsxwriter==3.0.3
    - yacs==0.1.8
    - yapf==0.31.0
    - yarl==1.6.3
    - zict==2.0.0
    - zipp==3.7.0
    - zope-interface==5.4.0

