name: scotg
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.47.0=hadc24fc_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.4.0=hb9d3cd8_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.10.15=h4a871b0_2_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - accelerate==1.1.1
    - aiofiles==23.2.1
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.11.0
    - aiosignal==1.3.1
    - altair==5.4.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.6.2.post1
    - astroid==3.3.8
    - async-timeout==5.0.1
    - attrs==24.2.0
    - blobfile==3.0.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - clip==1.0
    - continuum==1.2.7
    - contourpy==1.3.1
    - cosine-annealing-warmup==2.0
    - cycler==0.12.1
    - datasets==3.1.0
    - dill==0.3.8
    - distinctipy==1.3.4
    - distro==1.9.0
    - dodgy==0.2.1
    - exceptiongroup==1.2.2
    - fastapi==0.95.1
    - ffmpy==0.4.0
    - filelock==3.16.1
    - fire==0.7.0
    - flake8==7.1.1
    - flake8-polyfill==1.0.2
    - fonttools==4.54.1
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - ftfy==6.3.1
    - gitdb==4.0.12
    - gitpython==3.1.44
    - gradio==3.50.2
    - gradio-client==0.6.1
    - h11==0.14.0
    - h5py==3.12.1
    - httpcore==1.0.6
    - httpx==0.27.2
    - huggingface-hub==0.26.2
    - hydra-core==1.2.0
    - idna==3.10
    - imagehash==4.3.1
    - imageio==2.36.1
    - imagenetv2-pytorch==0.1
    - importlib-resources==6.4.5
    - iniconfig==2.0.0
    - isort==5.13.2
    - jieba==0.42.1
    - jinja2==3.1.4
    - jiter==0.7.1
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - littleutils==0.2.4
    - llama-models==0.0.50
    - llama-stack==0.0.52
    - lxml==5.3.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - mypy==1.14.1
    - mypy-extensions==1.0.0
    - narwhals==1.13.5
    - natsort==8.4.0
    - networkx==3.4.2
    - nltk==3.9.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-ml-py==13.580.82
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - nvitop==1.5.3
    - ogb==1.3.6
    - omegaconf==2.2.3
    - openai==1.54.4
    - orjson==3.10.11
    - outdated==0.2.2
    - packaging==24.2
    - pandas==2.2.3
    - peft==0.13.2
    - pep8-naming==0.10.0
    - pillow==10.4.0
    - platformdirs==4.3.6
    - pluggy==1.5.0
    - prompt-toolkit==3.0.48
    - propcache==0.2.0
    - prospector==1.13.3
    - protobuf==5.28.3
    - psutil==6.1.0
    - pyarrow==18.0.0
    - pycodestyle==2.12.1
    - pycryptodomex==3.21.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydocstyle==6.3.0
    - pydub==0.25.1
    - pyflakes==3.2.0
    - pygments==2.18.0
    - pylint==3.3.3
    - pylint-celery==0.3
    - pylint-django==2.6.1
    - pylint-flask==0.6
    - pylint-plugin-utils==0.8.2
    - pyparsing==3.2.0
    - pytest==8.3.4
    - pytest-mock==3.14.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-multipart==0.0.17
    - pytz==2024.2
    - pywavelets==1.8.0
    - pyyaml==6.0.2
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - requirements-detector==1.3.2
    - rich==13.9.4
    - rouge-chinese==1.0.3
    - rpds-py==0.21.0
    - safetensors==0.4.5
    - scikit-image==0.25.0
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - semver==3.0.2
    - sentencepiece==0.2.0
    - setoptconf-tmp==0.3.1
    - six==1.16.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - snowballstemmer==2.2.0
    - sse-starlette==2.1.3
    - starlette==0.26.1
    - sympy==1.13.1
    - tenacity==9.0.0
    - termcolor==2.5.0
    - threadpoolctl==3.5.0
    - tifffile==2024.12.12
    - tiktoken==0.8.0
    - timm==1.0.11
    - tokenizers==0.20.3
    - toml==0.10.2
    - tomli==2.2.1
    - tomlkit==0.13.2
    - torch==2.5.1
    - torchvision==0.20.1
    - tqdm==4.67.0
    - transformers==4.46.2
    - triton==3.1.0
    - trl==0.12.0
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3
    - uvicorn==0.32.0
    - wcwidth==0.2.13
    - websockets==11.0.3
    - wilds==2.0.0
    - xxhash==3.5.0
    - yarl==1.17.1

