name: l2p
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=22.1.2=pyhd8ed1ab_0
  - python=3.8.20=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - cycler==0.12.1
    - filelock==3.13.1
    - fonttools==4.57.0
    - fsspec==2024.6.1
    - ftfy==6.2.3
    - idna==3.10
    - jinja2==3.1.4
    - kiwisolver==1.4.7
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - mpmath==1.3.0
    - networkx==3.0
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nvtx-cu11==11.8.86
    - packaging==25.0
    - pillow==9.2.0
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - regex==2024.11.6
    - requests==2.32.3
    - six==1.17.0
    - sympy==1.13.1
    - timm==0.6.7
    - torch==2.4.1+cu118
    - torchaudio==2.4.1+cu118
    - torchprofile==0.0.4
    - torchvision==0.19.1+cu118
    - tqdm==4.67.1
    - triton==3.0.0
    - typing-extensions==4.13.2
    - urllib3==2.2.3
    - wcwidth==0.2.13

