hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}-${method}-2
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
train_file_path: ""
log_path: "metrics.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 32
initial_increment: 20  
increment: 3
scenario: "class"
dataset: "classroom"

method: "ZSCL"
lr: 7e-6
ls: 0.2
weight_decay: 0   # TODO
l2: 0   # TODO
ce_method:  # TODO
we: 1
avg_freq: 10
ref_model: 
ref_dataset: "conceptual_captions"
ref_sentences: "conceptual_captions"
L_g: 2
deep_g: 12
text_deep_replace_method: 'replace'
vision_deep_replace_method: 'accumulate'
visual: 1
n_runs: 5    
regularization_method: 'balance'


first:
second:
third:

a1:
a2:
a3: